import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,Brain,ChevronRight,Focus,Info,Layers3,Pause,RotateCcw,RotateCw,Search,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import AnatomyScene from './scene';
import {assetUrl} from './asset-url';
import {fold} from './fold';
import {useI18n} from '@/i18n/useI18n';
import type {Key} from '@/i18n/strings';
import {nameOf,useAnatomyNames} from '@/i18n/anatomyNames';
import {AtlasMemory} from '@/mnemo/AtlasMemory';
import {ReviewPanel} from '@/mnemo/ReviewPanel';
import {DEFAULT_VISIBLE,SYSTEMS,type Atlas,type Concept,type SceneState,type SystemId,type View} from './anatomy';
const ORGAN_KEY:Record<string,string>={'heart':'org.heart','liver':'org.liver','brain':'org.brain','stomach':'org.stomach','spleen':'org.spleen','pancreas':'org.pancreas','urinary bladder':'org.bladder','trachea':'org.trachea','diaphragm':'org.diaphragm'};
const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0};
export default function Home(){
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const searchPanel=useRef<HTMLElement>(null);
 const [quizLock,setQuizLock]=useState(false);
 const [studying,setStudying]=useState(false);

 const {t,lang}=useI18n();
 const names=useAnatomyNames(lang);
 // The display name for a concept or a mesh. Falls back to the atlas's
 // English, which is right everywhere except the quiz — the quiz filters
 // its pool instead, so it never reaches this fallback.
 const label=(id:string,english:string)=>nameOf(names,id,english);
 const [sex,setSex]=useState<'male'|'female'>('male');
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(initial),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|'review'|null>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null);
 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setState({...initial,visible:DEFAULT_VISIBLE});fetch(assetUrl(sex==='female'?'/models/atlas-female.json':'/models/atlas.json'),{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('The anatomy catalogue could not be loaded.');return r.json();}).then(data=>{const at=data as Atlas;const muscle=at.parts.filter(p=>p.system==='muscular').length/Math.max(1,at.parts.length);const hasSkin=at.parts.some(p=>p.system==='integumentary');if(hasSkin&&muscle<.05)setState(st=>({...st,visible:[...st.visible,'integumentary']}));setAtlas(at);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[sex]);
 // The panel closes on Escape, on its X, or on a click OUTSIDE it — and
 // nowhere else. It used to close whenever the combobox asked to close, but
 // the combobox asks for NINE different reasons, and pressing the input to
 // start typing is one of them: it reads as an outside-press because the
 // input sits outside the popup. So the panel tore itself down at the exact
 // moment someone clicked to type, and search was unusable.
 // pointerdown in CAPTURE, not mousedown: a host canvas that calls
 // preventDefault on pointerdown to pan suppresses the compatibility mouse
 // events entirely, and this cartridge runs inside one.
 useEffect(()=>{if(panel!=='search')return;const away=(e:Event)=>{const t=e.target as Node|null;if(!t)return;
  const inPanel=searchPanel.current?.contains(t);
  // The popup is portalled out of the panel, and the button that opened it
  // counts as INSIDE — otherwise the toggle closes what it just opened.
  const inResults=(t as Element).nodeType===1&&!!(t as Element).closest?.('.anatomy-search-results');
  const onTrigger=(t as Element).nodeType===1&&!!(t as Element).closest?.('.top-actions');
  if(!inPanel&&!inResults&&!onTrigger)setPanel(null);};
  document.addEventListener('pointerdown',away,true);return()=>document.removeEventListener('pointerdown',away,true);},[panel]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(SYSTEMS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const activeSystems=SYSTEMS.filter(s=>counts[s.id]>0);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=SYSTEMS.find(s=>s.id===selected?.system);
 const visibleCount=atlas?.parts.filter(p=>state.isolate?state.selected.includes(p.id):state.visible.includes(p.system)||state.selected.includes(p.id)).length??0;
 const results=useMemo(()=>{if(!atlas)return[];const term=fold(query.trim());if(!term)return ['heart','brain','liver','stomach','spleen','pancreas','urinary bladder','trachea'].map(name=>atlas.concepts.find(c=>c.name.toLowerCase()===name)).filter((x):x is Concept=>!!x);return atlas.concepts.filter(c=>fold(c.name).includes(term)||fold(label(c.id,c.name)).includes(term)||fold(c.id).includes(term)).sort((a,b)=>a.name.length-b.name.length).slice(0,80);},[atlas,query,names]);
 const choose=(c:Concept)=>{setChosen(c);setState(s=>({...s,selected:c.elements,isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas]);
 const choosePart=(id:string)=>{if(quizLock)return;const p=parts.get(id);if(!p)return;setChosen({id:p.conceptId,name:p.name,elements:[id]});setState(s=>({...s,selected:[id],isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 const toggle=(id:SystemId)=>{setDetails(false);setState(s=>({...s,selected:[],isolate:false,visible:s.visible.includes(id)?s.visible.filter(x=>x!==id):[...s.visible,id]}));};
 const reset=()=>{setState(s=>({...initial,visible:DEFAULT_VISIBLE,reset:s.reset+1}));setChosen(null);setDetails(false);setPanel(null);};
 const openPanel=(next:'layers'|'search'|'review')=>{setDetails(false);setPanel(p=>p===next?null:next);};
 return <main className={`studio ${studying?'studying':''}`}>
  {atlas&&<AnatomyScene atlas={atlas} state={{...state,inspectorOpen:details&&selectedParts.length>0}} onSelect={choosePart} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError}/>}
  <div className="vignette"/>
  <header className="identity"><div className="eyebrow"><span className="status-dot"/> {t('app.eyebrow')}</div><h1>{t('ui.title')}<Badge variant="outline" className="edition">3D</Badge></h1><div className="identity-meta">{atlas?atlas.parts.length.toLocaleString():'—'} {t('app.pieces')} <span>·</span> {sex==='female'?'HuBMAP HRA':'BodyParts3D'}</div><div className="anatomy-choice" role="group" aria-label={t('app.body.group')}>{(['male','female'] as const).map(s2=><Button variant="ghost" key={s2} className={sex===s2?'active':''} aria-pressed={sex===s2} onClick={()=>{if(s2!==sex)setSex(s2);}}>{t(s2==='male'?'app.body.male':'app.body.female')}</Button>)}</div></header>
  <nav className="top-actions" aria-label={t('a11y.panels')}><Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label={t('a11y.search')}><Search size={18}/><span>{t('ui.find')}</span><kbd>/</kbd></Button><Button variant="ghost" className={panel==='review'?'active':''} onClick={()=>{setDetails(false);setPanel(p=>p==='review'?null:'review');}} aria-label={t('review.open')}><Brain size={18}/><span>{t('review.title')}</span></Button><Button variant="ghost" className="icon-button" aria-label={t('a11y.about')} onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}><Info size={18}/></Button></nav>
  <section className={`layers-panel glass ${panel==='layers'?'mobile-open':''}`} aria-label={t('a11y.layers')}>
   <div className="panel-heading"><span>{t('ui.systems')}</span><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label={t('a11y.closeSystems')}><X size={18}/></Button><Badge variant="secondary" className="desktop-only small-number">{activeSystems.length}</Badge></div>
   <div className="layer-presets"><Button variant="ghost" aria-pressed={activeSystems.every(x=>state.visible.includes(x.id))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:activeSystems.map(x=>x.id)}))}>{t('ui.all')}</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='skeletal'} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['skeletal']}))}>{t('ui.skeletonPreset')}</Button><Button variant="ghost" aria-pressed={state.visible.length===6&&['cardiac','respiratory','digestive','urinary','endocrine','reproductive'].every(id=>state.visible.includes(id as SystemId))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['cardiac','respiratory','digestive','urinary','endocrine','reproductive']}))}>{t('ui.organsPreset')}</Button></div>
   <div className="system-list">{activeSystems.map(s=><div className={`system-row ${state.visible.includes(s.id)?'enabled':''}`} key={s.id}><Button variant="ghost" className="system-name" title={t('a11y.showOnly', { name: t(`system.${s.id}` as Key).toLowerCase() })} onClick={()=>setState(v=>({...v,visible:[s.id],isolate:false,selected:[]}))}><span className="system-dot" style={{background:s.color}}/>{t(`system.${s.id}` as Key)}<span className="system-count">{counts[s.id]}</span></Button><Switch checked={state.visible.includes(s.id)} onCheckedChange={()=>toggle(s.id)} aria-label={t('a11y.show', { name: t(`system.${s.id}` as Key).toLowerCase() })} /></div>)}</div>
   <div className="panel-foot"><span>{t('ui.visible', { n: visibleCount.toLocaleString() })}</span><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false}))}>{t('ui.hideAll')}</Button></div>
  </section>
  {panel==='search'&&<section ref={searchPanel} className="search-panel glass" aria-label={t('a11y.findAnatomy')}><div className="panel-heading"><span>{t('ui.find')}</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label={t('a11y.closeSearch')}><X size={18}/></Button></div><Combobox<Concept> items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={c=>c.name} filter={null} open onOpenChange={(next,details)=>{if(!next&&details?.reason==='escape-key')setPanel(null);}}><ComboboxInput autoFocus placeholder={t('ui.searchPlaceholder')} aria-label={t('a11y.searchInput')} showTrigger={false} onKeyDown={e=>{if(e.key!=='Enter'||e.nativeEvent.isComposing)return;if(document.querySelector('.anatomy-search-results [data-slot=combobox-item][data-highlighted]'))return;const first=results[0];if(first){e.preventDefault();choose(first);}}}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>{t('ui.noMatch')}</ComboboxEmpty><ComboboxList>{(c:Concept)=><ComboboxItem key={c.id} value={c}><span className="search-result-name">{label(c.id,c.name)}</span><span className="small-number">{c.elements.length} {c.elements.length===1?t('ui.piece'):t('ui.pieces')}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?t('ui.searchHintTyping'):t('ui.searchHintEmpty')}</p></section>}
  {panel==='review'&&atlas&&<ReviewPanel atlas={atlas} body={sex} source={sex==='female'?'HuBMAP HRA':'BodyParts3D'}
   onShow={els=>{setQuizLock(true);setChosen(null);setDetails(false);setState(v=>({...v,selected:els,isolate:true,explode:0,rotate:false}));}}
   onInspect={c=>{setQuizLock(false);choose(c);setPanel('review');}}
   onStudyingChange={setStudying}
   onClose={()=>{setQuizLock(false);setPanel(null);setState(v=>({...v,selected:[],isolate:false}));}}/>}
  <nav className="view-controls glass" aria-label={t('a11y.camera')}>{(['three-quarter','front','side','back'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} disabled={state.explode>.8&&v!=='front'} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1,rotate:false}))} title={t('a11y.view', { view: v })} aria-label={t('a11y.view', { view: v })}><span>{['¾','F','S','B'][i]}</span></Button>)}<i/><Button variant="ghost" disabled={state.explode>=.4} aria-label={state.rotate?t('a11y.pause'):t('a11y.rotate')} title={t('a11y.autoRotate')} className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" aria-label={t('a11y.resetAll')} title={t('ui.reset')} onClick={reset}><RotateCcw size={17}/></Button></nav>
  <div className="scene-caption"><span className="caption-line"/><span>{state.isolate?(chosen?.name??'SELECTED STRUCTURE'):state.explode>.95?'ANATOMICAL INVENTORY':state.explode>.05?'SEPARATED STRUCTURES':t(sex==='female'?'app.caption.female':'app.caption.male')}</span><span className="caption-line"/></div>
  <div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>openPanel('layers')} aria-label={t('a11y.openLayers')}><Layers3 size={20}/><span>{t('ui.systems')}</span></Button><div className="explode-control"><div className="explode-label"><label id="explode-label">{t('ui.explode')}</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100,view:(Array.isArray(v)?v[0]:v)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><span>{t('ui.assembled')}</span><span>{t('ui.everyPiece')}</span></div></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label={t('a11y.assembleReset')}><RotateCcw size={18}/><span>{t('ui.reset')}</span></Button></div>
  <footer className="studio-footer"><span>{state.explode>.8?t('ui.hintPan'):t('ui.hintOrbit')} <b>·</b> {t('ui.hintZoom')} <b>·</b> {t('ui.hintTap')}</span><Button variant="ghost" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>{t('ui.credits')} <ArrowUpRight size={12}/></Button></footer>
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>{t('ui.preparing')}</strong><span>{t('ui.loading', { pct: progress, n: atlas?.parts.length.toLocaleString() ?? '—' })}</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p><Button variant="ghost" onClick={()=>location.reload()}>{t('ui.reload')}</Button></div>}
  <Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''}`} showCloseButton={true}><div className="detail-header"><div className="detail-accent" style={{background:system?.color}}/><div className="eyebrow">{selected? t(`system.${selected.system}` as Key) : ''}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{chosen?label(chosen.id,chosen.name):''}</SheetTitle></div><div className="detail-scroll" key={`${chosen?.id}-${state.isolate}`}><SheetDescription className="structure-description">{chosen&&selected?t((ORGAN_KEY[chosen.name.toLowerCase()]??`sys.${selected.system}`) as Key):''}</SheetDescription>{chosen&&!ORGAN_KEY[chosen.name.toLowerCase()]&&<span className="context-note">{t('ui.contextNote')}</span>}<div className="structure-meta"><span>{t('ui.atlasRef')}<strong>{chosen?.id}</strong></span><span>{t('ui.selectedPieces')}<strong>{state.selected.length.toLocaleString()}</strong></span></div><AtlasMemory concept={chosen}/>{selectedParts.length>1&&<div className="member-list"><h3>{t('ui.included')}</h3>{selectedParts.slice(0,50).map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}><span>{label(p.conceptId,p.name)}</span><ChevronRight size={14}/></Button>)}{selectedParts.length>50&&<p>{t('ui.andMorePieces', { n: selectedParts.length-50 })}</p>}</div>}<a className="source-link" href="https://lifesciencedb.jp/bp3d/" target="_blank" rel="noreferrer">{t('ui.viewSource')} <ArrowUpRight size={14}/></a></div><div className="detail-actions"><Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?t('ui.showAround'):t('ui.isolate')}<ChevronRight size={16}/></Button><Button variant="ghost" className="secondary-action" onClick={()=>{setState(s=>({...s,selected:[],isolate:false}));setDetails(false);}}>{t('ui.clear')}</Button></div></SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">{t('about.eyebrow')}</div><SheetTitle className="structure-title">{t('about.title')}</SheetTitle><SheetDescription>{t(sex==='female'?'about.leadFemale':'about.leadMale')}</SheetDescription><div className="about-copy"><p><strong>{t(sex==='female'?'about.headFemale':'about.headMale')}</strong><br/>{t(sex==='female'?'about.bodyFemale':'about.bodyMale')}</p><p>{t('about.incomplete')}</p><p>{t('about.disclaimer')}</p><h3>{t('about.source')}</h3><p>BodyParts3D, © The Database Center for Life Science licensed under CC Attribution 4.0 International.</p><h3>{t('about.femaleRef')}</h3><p>Kristen Browne and Heidi Schlehlein, <em>3D Reference Organ Set for Female, v1.5</em> (2023), Human Reference Atlas / HuBMAP. Licensed under CC Attribution 4.0 International.</p><a href="https://doi.org/10.48539/HBM352.BTSQ.586" target="_blank" rel="noreferrer">{t('about.femaleDoi')} <ArrowUpRight size={14}/></a><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html" target="_blank" rel="noreferrer">{t('about.datasetLicense')} <ArrowUpRight size={14}/></a><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html" target="_blank" rel="noreferrer">{t('about.originalGeometry')} <ArrowUpRight size={14}/></a><a href="https://academic.oup.com/nar/article/37/suppl_1/D782/1000752" target="_blank" rel="noreferrer">{t('about.publication')} <ArrowUpRight size={14}/></a></div></SheetContent></Sheet>
 </main>;
}
